Task1
tonyaraujop/web-app-cm42 pull request #1
Opened 2022-02-08 13:15 UTC by tonyaraujop

2022-02-08 16:15 UTC, fabiosammy commented on src/index.html
> +    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
Faltou a font nos settings...

2022-02-08 16:55 UTC, tonyaraujop commented on src/index.html
> +    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
Verdade. Mas eu corrigi isso logo quando fui fazer a task 2, que inclusive já tem PR.

2022-02-09 01:20 UTC, iagodahlem requested changes

2022-02-09 01:20 UTC, iagodahlem commented on src/styles/index.css
> +@import 'elements/_elements.css';
Os imports tem que seguir a mesma ordem da pirâmide, então as settings sempre vem primeiro. Lembra do efeito cascata.

2022-02-09 01:20 UTC, iagodahlem commented on src/styles/settings/_default.css
> +}
Isso não faz parte das settings, lembra das regras de cada camada.

2022-02-09 01:20 UTC, iagodahlem commented on src/styles/settings/_default.css
> +:root{
💅

```suggestion
:root {
```

2022-02-09 11:21 UTC, tonyaraujop commented on src/styles/index.css
> +@import 'elements/_elements.css';
Perfeito. Eu fiz essa correção na PR da Task 3 se não me engano. De qualquer forma já foi corrigido.

2022-02-09 11:22 UTC, tonyaraujop commented on src/styles/settings/_default.css
> +}
Eu devo colocar as fontes/tamanhos como variáveis globais então?

2022-02-09 19:48 UTC, iagodahlem commented on src/styles/settings/_default.css
> +}
Toda variável é global em CSS, então primeiro sim, esses valores devem estar em variáveis. Já a definição desse CSS não faz parte dessa de configurações, e sim da camada de elements.

2022-02-09 19:49 UTC, iagodahlem commented on src/styles/index.css
> +@import 'elements/_elements.css';
Sempre bom corrigir na PR atual, senão tu vai estar mergeando código errado na main.

2022-02-09 20:15 UTC, tonyaraujop commented on src/styles/settings/_default.css
> +}
Ok. Farei essas alterações.

2022-02-09 20:29 UTC, merged